---
apiVersion: v1
kind: Secret
metadata:
  name: csi-s3-secret
  namespace: kube-system
stringData:
  accessKeyID: "asdqwe123"
  secretAccessKey: "asdqwe123"
  endpoint: "https://storage.yandexcloud.net"
  region: ""
