---
apiVersion: v1
kind: Pod
metadata:
  name: node-debug
  namespace: homework
spec:
  nodeName: cl13oiib4apj0v1snph3-aqiv
  hostPID: true
  hostNetwork: true
  containers:
  - name: debug
    image: nicolaka/netshoot
    command: ["/bin/bash","-c","sleep 1d"]
    securityContext:
      privileged: true
      runAsUser: 0
    volumeMounts:
    - name: host-root
      mountPath: /host
      readOnly: true
  volumes:
  - name: host-root
    hostPath:
      path: /
  restartPolicy: Never
