---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-distroless
  namespace: homework
  labels:
    app: nginx-distroless
spec:
  containers:
  - name: nginx
    image: kyos0109/nginx-distroless:latest
    imagePullPolicy: IfNotPresent
    ports:
      - containerPort: 80
