apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: ss-vault
  namespace: vault
spec:
  provider:
    vault:
      server: "http://vault:8200"
      path: "otus"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "otus"
          serviceAccountRef:
            name: "vault-auth"
