apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: nginx
    otus: homework
spec:
  selector:
{{- if .Values.selector }}
{{ toYaml .Values.selector | indent 4 }}
{{- else }}
    otus: homework
{{- end }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.nginx.listenPort | default 8000 }}
