apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: homework
data:
  default.conf: |
    server {
      listen 8000;
      server_name _;
      location / {
        root   /homework;
        index  index.html index.htm;
      }
    }
